version: '3.7'

volumes:
  wordpress_v:
    driver: local
    driver_opts:
      type: none
      device: /home/htaheri/data/wordpress
      o: bind
  mariadb_v:
    driver: local
    driver_opts:
      type: none
      device: /home/htaheri/data/mariadb
      o: bind

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb/
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_v:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - wordpress_v:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/
    ports:
      - "443:443"
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_v:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception

networks:
  inception:
    name: inception
    driver: bridge
