version: '3.8'

services:
  db:
    build: ./db
    container_name: wordpress_db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
wordpress:
    build: ./wordpress
    container_name: wordpress
    depends_on:
      - db
    ports:
      - "8000:80"
    restart: always
    env_file:
      - .env
    volumes:
      - ./wordpress:/var/www/html
nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - wordpress
    restart: always
volumes:
  db_data:
  wordpress_data:

networks:
  inception:
    name: inception